### ISSUE TITLE
Mark As Read For Topics

### ISSUE THREAD

**Issue by mackey256** [jaysylvester/comitium#151] opened 2015-11-11 14:21 UTC
It would be nice if we had a button to mark all topics as read in a discussion category so when you return you only see unread on the topics that have been updated since your last visit.

Currently only topics you've visited will appear unread any topic you didn't read will constantly have an unread notification on it.

**Comment by mackey256** [comment] 2015-11-11 16:53
This could actually be covered by issue #128

**Comment by jaysylvester** [comment] 2018-04-23 21:16
Dupe of #57.

**Closed by jaysylvester** 2018-04-23 21:16 UTC
